services: # All services automatically has access to .env variables
  client:
    build: 
      context: .
      dockerfile: apps/client/Dockerfile
    container_name: opencitadel-client
    ports:
      - ${PORT}:80 # 80 exposed in container by nginx image.
    depends_on:
      - server

  server:
    build: 
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: opencitadel-server
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - database

  database:
    image: postgres:18-alpine # Exposed on port 5432 in docker network by default
    container_name: opencitadel-database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data: # Volume for the database data